version: '2.3'
services:

  test-process:
    hostname: test-process
    image: dbtest-process
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - sqlite
      - mariadb
      - postgres

  sqlite:
    hostname: sqlite
    image: dockerpinata/sqlite

  mariadb:
    hostname: mariadb
    image:  mariadb

  postgres:
    hostname: postgres
    image: postgres
