version: '2.3'
services:

  test-process:
    hostname: test-process
    image: dbtest-process
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - mariadb
      - postgres

  mariadb:
    hostname: mariadb
    image:  mariadb

  postgres:
    hostname: postgres
    image: postgres
